name: aciminimal
services:
  acimin:
    image: aciminimal:latest
    build:
      context: .
      tags:
      - ops5containers.azurecr.io/dev/aciminimal
    container_name: acimin
    restart: always
    ports:
      - "80:8080"
      - "443:8081"
