name: Build docker image for Windows Server 2022
on:
  workflow_dispatch:
    inputs:
      image-name: 
        description: Image name
        type: string
        default: aci-min-win22
      image-tag: 
        description: Image tag
        type: string
        default: latest
      acr-name:
        description: Name of the Azure container registry to push to
        type: string
        default: ops5containers

env:
  acr-server: '${{ inputs.acr-name }}.azurecr.io'
  
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set FULL_IMAGE_NAME
      run: |
        "FULL_IMAGE_NAME='${{ env.acr-server }}/%{{ inputs.image-name }}:${{ inputs.image-tag }}'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Login to azure
      uses: azure/login@v2.1.1
      with:
        creds: '${{ secrets.DEPLOY_SP }}'
        enable-AzPSSession: true
  
    - name: Build the Docker image
      run: docker build . --file win2022.dockerfile --tag ${{ inputs.image-name }}:${{ inputs.image-tag }} --tag "${env:FULL_IMAGE_NAME}"

    - name: Push to ACR
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az acr login --name ${{ inputs.acr-name }}
          docker push "${env:FULL_IMAGE_NAME}"
        azPSVersion: latest

